package io.celox.clipvault.ui.settings

import android.content.Intent
import android.os.Bundle
import android.widget.Toast
import androidx.activity.compose.setContent
import androidx.activity.enableEdgeToEdge
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.WindowInsets
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.safeDrawing
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.layout.windowInsetsPadding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.ChevronRight
import androidx.compose.material.icons.filled.Fingerprint
import androidx.compose.material.icons.filled.Info
import androidx.compose.material.icons.filled.Key
import androidx.compose.material.icons.filled.Lock
import androidx.compose.material.icons.filled.Shield
import androidx.compose.material.icons.filled.Security
import androidx.compose.material.icons.filled.Visibility
import androidx.compose.material.icons.filled.VisibilityOff
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Switch
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.material3.TopAppBar
import androidx.compose.material3.TopAppBarDefaults
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.text.input.VisualTransformation
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.fragment.app.FragmentActivity
import io.celox.clipvault.ClipVaultApp
import io.celox.clipvault.ui.about.AboutActivity
import io.celox.clipvault.ui.license.LicenseActivity
import io.celox.clipvault.ui.theme.ClipVaultTheme
import java.security.SecureRandom

class SettingsActivity : FragmentActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        enableEdgeToEdge()

        setContent {
            ClipVaultTheme {
                val app = application as ClipVaultApp
                val ksm = app.keyStoreManager
                var appLockEnabled by remember { mutableStateOf(ksm.isAppLockEnabled()) }
                var biometricEnabled by remember { mutableStateOf(ksm.isAppLockBiometricEnabled()) }
                var passwordGenerated by remember { mutableStateOf(ksm.isAppLockPasswordGenerated()) }
                var showAppLockDialog by remember { mutableStateOf(false) }
                var showDisableAppLockDialog by remember { mutableStateOf(false) }
                var showChangePasswordDialog by remember { mutableStateOf(false) }

                val versionName = try {
                    packageManager.getPackageInfo(packageName, 0).versionName ?: "?"
                } catch (_: Exception) { "?" }

                SettingsScreen(
                    appLockEnabled = appLockEnabled,
                    biometricEnabled = biometricEnabled,
                    passwordGenerated = passwordGenerated,
                    isLicenseActivated = app.licenseManager.isActivated(),
                    licenseEmail = app.licenseManager.getActivatedEmail(),
                    versionName = versionName,
                    onBack = { finish() },
                    onToggleAppLock = { enabled ->
                        if (enabled) {
                            showAppLockDialog = true
                        } else {
                            showDisableAppLockDialog = true
                        }
                    },
                    onChangePassword = { showChangePasswordDialog = true },
                    onToggleBiometric = { enabled ->
                        ksm.setAppLockBiometricEnabled(enabled)
                        biometricEnabled = enabled
                    },
                    onOpenLicense = {
                        startActivity(Intent(this, LicenseActivity::class.java))
                    },
                    onOpenAbout = {
                        startActivity(Intent(this, AboutActivity::class.java))
                    }
                )

                if (showAppLockDialog) {
                    AppLockSetupDialog(
                        onDismiss = { showAppLockDialog = false },
                        onConfirmGenerated = {
                            showAppLockDialog = false
                            val generatedPw = generateSecurePassword()
                            ksm.storeAppLockPassword(generatedPw)
                            ksm.setAppLockPasswordGenerated(true)
                            ksm.setAppLockBiometricEnabled(true)
                            ksm.setAppLockEnabled(true)
                            appLockEnabled = true
                            passwordGenerated = true
                            biometricEnabled = true
                            // UI feedback via toggle state change
                        },
                        onConfirmManual = { password ->
                            showAppLockDialog = false
                            ksm.storeAppLockPassword(password)
                            ksm.setAppLockPasswordGenerated(false)
                            ksm.setAppLockEnabled(true)
                            appLockEnabled = true
                            passwordGenerated = false
                            // UI feedback via toggle state change
                        }
                    )
                }

                if (showDisableAppLockDialog) {
                    AlertDialog(
                        onDismissRequest = { showDisableAppLockDialog = false },
                        title = { Text("App-Sperre deaktivieren?") },
                        text = { Text("Die App ist danach ohne Authentifizierung zugänglich. Die Datenbank bleibt verschlüsselt.") },
                        confirmButton = {
                            TextButton(onClick = {
                                showDisableAppLockDialog = false
                                ksm.clearAppLock()
                                appLockEnabled = false
                                passwordGenerated = false
                                biometricEnabled = ksm.isAppLockBiometricEnabled()
                                // UI feedback via toggle state change
                            }) {
                                Text("Deaktivieren", color = MaterialTheme.colorScheme.error)
                            }
                        },
                        dismissButton = {
                            TextButton(onClick = { showDisableAppLockDialog = false }) {
                                Text("Abbrechen")
                            }
                        }
                    )
                }

                if (showChangePasswordDialog) {
                    ChangePasswordDialog(
                        onDismiss = { showChangePasswordDialog = false },
                        onConfirm = { oldPw, newPw ->
                            showChangePasswordDialog = false
                            val stored = ksm.retrieveAppLockPassword()
                            if (stored == oldPw) {
                                ksm.storeAppLockPassword(newPw)
                                // Dialog closes as confirmation
                            } else {
                                Toast.makeText(this, "Falsches Passwort", Toast.LENGTH_SHORT).show()
                            }
                        }
                    )
                }
            }
        }
    }

    private fun generateSecurePassword(): String {
        val chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%&*"
        val random = SecureRandom()
        return (1..32).map { chars[random.nextInt(chars.length)] }.joinToString("")
    }
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun SettingsScreen(
    appLockEnabled: Boolean,
    biometricEnabled: Boolean,
    passwordGenerated: Boolean,
    isLicenseActivated: Boolean,
    licenseEmail: String?,
    versionName: String,
    onBack: () -> Unit,
    onToggleAppLock: (Boolean) -> Unit,
    onChangePassword: () -> Unit,
    onToggleBiometric: (Boolean) -> Unit,
    onOpenLicense: () -> Unit,
    onOpenAbout: () -> Unit
) {
    Scaffold(
        modifier = Modifier.windowInsetsPadding(WindowInsets.safeDrawing),
        topBar = {
            TopAppBar(
                title = { Text("Einstellungen", fontWeight = FontWeight.Bold) },
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(Icons.AutoMirrored.Filled.ArrowBack, contentDescription = "Zurück")
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(
                    containerColor = MaterialTheme.colorScheme.surface
                )
            )
        }
    ) { innerPadding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(innerPadding)
                .verticalScroll(rememberScrollState())
        ) {
            // --- Security Section ---
            SectionHeader("Sicherheit")

            // DB encryption info (always on, not toggleable)
            SettingsInfoItem(
                icon = Icons.Default.Security,
                title = "Datenbank-Verschlüsselung",
                subtitle = "Immer aktiv (AES-256)"
            )

            // App lock toggle
            SettingsToggleItem(
                icon = Icons.Default.Lock,
                title = "App-Sperre",
                subtitle = when {
                    appLockEnabled && passwordGenerated -> "Gesperrt (Fingerprint)"
                    appLockEnabled -> "Gesperrt (Passwort)"
                    else -> "Deaktiviert"
                },
                checked = appLockEnabled,
                onCheckedChange = onToggleAppLock
            )

            if (appLockEnabled) {
                // "Passwort ändern" only for manual passwords
                if (!passwordGenerated) {
                    SettingsClickItem(
                        icon = Icons.Default.Key,
                        title = "Passwort ändern",
                        subtitle = "App-Sperr-Passwort ändern",
                        onClick = onChangePassword
                    )
                }

                // Biometric toggle
                if (passwordGenerated) {
                    SettingsInfoItem(
                        icon = Icons.Default.Fingerprint,
                        title = "Biometrische Sperre",
                        subtitle = "Immer aktiv (automatisches Passwort)"
                    )
                } else {
                    SettingsToggleItem(
                        icon = Icons.Default.Fingerprint,
                        title = "Biometrische Sperre",
                        subtitle = if (biometricEnabled) "Fingerabdruck/Gesicht zum Entsperren" else "Deaktiviert",
                        checked = biometricEnabled,
                        onCheckedChange = onToggleBiometric
                    )
                }
            }

            HorizontalDivider(modifier = Modifier.padding(horizontal = 16.dp, vertical = 8.dp))

            // --- License Section ---
            SectionHeader("Lizenz")

            SettingsClickItem(
                icon = Icons.Default.Shield,
                title = if (isLicenseActivated) "Lizenz aktiv" else "Lizenz aktivieren",
                subtitle = if (isLicenseActivated) licenseEmail ?: "" else "Kostenlose Version (max. 10 Clips)",
                onClick = onOpenLicense
            )

            HorizontalDivider(modifier = Modifier.padding(horizontal = 16.dp, vertical = 8.dp))

            // --- Info Section ---
            SectionHeader("Info")

            SettingsClickItem(
                icon = Icons.Default.Info,
                title = "Über ClipVault",
                subtitle = "Version $versionName",
                onClick = onOpenAbout
            )
        }
    }
}

@Composable
fun SectionHeader(title: String) {
    Text(
        text = title,
        style = MaterialTheme.typography.labelLarge,
        color = MaterialTheme.colorScheme.primary,
        fontWeight = FontWeight.Bold,
        modifier = Modifier.padding(start = 16.dp, top = 16.dp, bottom = 4.dp)
    )
}

@Composable
fun SettingsToggleItem(
    icon: ImageVector,
    title: String,
    subtitle: String,
    checked: Boolean,
    onCheckedChange: (Boolean) -> Unit
) {
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .clickable { onCheckedChange(!checked) }
            .padding(horizontal = 16.dp, vertical = 12.dp),
        verticalAlignment = Alignment.CenterVertically
    ) {
        Icon(icon, contentDescription = null, tint = MaterialTheme.colorScheme.onSurfaceVariant)
        Spacer(modifier = Modifier.width(16.dp))
        Column(modifier = Modifier.weight(1f)) {
            Text(title, style = MaterialTheme.typography.bodyLarge)
            Text(subtitle, style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant)
        }
        Switch(checked = checked, onCheckedChange = onCheckedChange)
    }
}

@Composable
fun SettingsClickItem(
    icon: ImageVector,
    title: String,
    subtitle: String,
    onClick: () -> Unit
) {
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .clickable(onClick = onClick)
            .padding(horizontal = 16.dp, vertical = 12.dp),
        verticalAlignment = Alignment.CenterVertically
    ) {
        Icon(icon, contentDescription = null, tint = MaterialTheme.colorScheme.onSurfaceVariant)
        Spacer(modifier = Modifier.width(16.dp))
        Column(modifier = Modifier.weight(1f)) {
            Text(title, style = MaterialTheme.typography.bodyLarge)
            Text(subtitle, style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant)
        }
        Icon(Icons.Default.ChevronRight, contentDescription = null, tint = MaterialTheme.colorScheme.onSurfaceVariant.copy(alpha = 0.5f))
    }
}

@Composable
fun SettingsInfoItem(
    icon: ImageVector,
    title: String,
    subtitle: String
) {
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .padding(horizontal = 16.dp, vertical = 12.dp),
        verticalAlignment = Alignment.CenterVertically
    ) {
        Icon(icon, contentDescription = null, tint = MaterialTheme.colorScheme.onSurfaceVariant)
        Spacer(modifier = Modifier.width(16.dp))
        Column(modifier = Modifier.weight(1f)) {
            Text(title, style = MaterialTheme.typography.bodyLarge)
            Text(subtitle, style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant)
        }
    }
}

// --- App Lock Setup Dialog ---

@Composable
fun AppLockSetupDialog(
    onDismiss: () -> Unit,
    onConfirmGenerated: () -> Unit,
    onConfirmManual: (String) -> Unit
) {
    var showManualFields by remember { mutableStateOf(false) }
    var password by remember { mutableStateOf("") }
    var confirmPassword by remember { mutableStateOf("") }
    var passwordVisible by remember { mutableStateOf(false) }
    var error by remember { mutableStateOf<String?>(null) }

    AlertDialog(
        onDismissRequest = onDismiss,
        title = { Text("App-Sperre aktivieren") },
        text = {
            Column {
                if (!showManualFields) {
                    Text(
                        "Wähle wie die App geschützt werden soll:",
                        style = MaterialTheme.typography.bodySmall,
                        color = MaterialTheme.colorScheme.onSurfaceVariant
                    )

                    Spacer(modifier = Modifier.height(20.dp))

                    // Option 1: Generated + Fingerprint
                    Button(
                        onClick = onConfirmGenerated,
                        modifier = Modifier.fillMaxWidth(),
                        shape = RoundedCornerShape(12.dp)
                    ) {
                        Icon(Icons.Default.Fingerprint, contentDescription = null, modifier = Modifier.size(20.dp))
                        Spacer(modifier = Modifier.width(8.dp))
                        Text("Mit Fingerprint sichern")
                    }

                    Spacer(modifier = Modifier.height(4.dp))

                    Text(
                        "Entsperre nur mit Fingerprint oder Geräte-PIN.",
                        style = MaterialTheme.typography.bodySmall,
                        color = MaterialTheme.colorScheme.onSurfaceVariant,
                        textAlign = TextAlign.Center,
                        modifier = Modifier.fillMaxWidth()
                    )

                    Spacer(modifier = Modifier.height(20.dp))

                    // Option 2: Manual password
                    OutlinedButton(
                        onClick = { showManualFields = true },
                        modifier = Modifier.fillMaxWidth(),
                        shape = RoundedCornerShape(12.dp)
                    ) {
                        Icon(Icons.Default.Key, contentDescription = null, modifier = Modifier.size(20.dp))
                        Spacer(modifier = Modifier.width(8.dp))
                        Text("Eigenes Passwort")
                    }
                } else {
                    Text(
                        "Lege ein Passwort fest, um die App zu sperren.",
                        style = MaterialTheme.typography.bodySmall,
                        color = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                    Spacer(modifier = Modifier.height(16.dp))
                    OutlinedTextField(
                        value = password,
                        onValueChange = { password = it; error = null },
                        label = { Text("Passwort") },
                        singleLine = true,
                        visualTransformation = if (passwordVisible) VisualTransformation.None else PasswordVisualTransformation(),
                        trailingIcon = {
                            IconButton(onClick = { passwordVisible = !passwordVisible }) {
                                Icon(
                                    if (passwordVisible) Icons.Default.VisibilityOff else Icons.Default.Visibility,
                                    contentDescription = null
                                )
                            }
                        },
                        modifier = Modifier.fillMaxWidth(),
                        shape = RoundedCornerShape(12.dp)
                    )
                    Spacer(modifier = Modifier.height(8.dp))
                    OutlinedTextField(
                        value = confirmPassword,
                        onValueChange = { confirmPassword = it; error = null },
                        label = { Text("Passwort bestätigen") },
                        singleLine = true,
                        visualTransformation = if (passwordVisible) VisualTransformation.None else PasswordVisualTransformation(),
                        modifier = Modifier.fillMaxWidth(),
                        shape = RoundedCornerShape(12.dp)
                    )
                    if (error != null) {
                        Spacer(modifier = Modifier.height(8.dp))
                        Text(error!!, color = MaterialTheme.colorScheme.error, style = MaterialTheme.typography.bodySmall)
                    }
                }
            }
        },
        confirmButton = {
            if (showManualFields) {
                TextButton(onClick = {
                    when {
                        password.length < 4 -> error = "Mindestens 4 Zeichen"
                        password != confirmPassword -> error = "Passwörter stimmen nicht überein"
                        else -> onConfirmManual(password)
                    }
                }) {
                    Text("Aktivieren")
                }
            }
        },
        dismissButton = {
            TextButton(onClick = {
                if (showManualFields) {
                    showManualFields = false
                    password = ""
                    confirmPassword = ""
                    error = null
                } else {
                    onDismiss()
                }
            }) {
                Text(if (showManualFields) "Zurück" else "Abbrechen")
            }
        }
    )
}

// --- Change Password Dialog ---

@Composable
fun ChangePasswordDialog(
    onDismiss: () -> Unit,
    onConfirm: (String, String) -> Unit
) {
    var oldPassword by remember { mutableStateOf("") }
    var newPassword by remember { mutableStateOf("") }
    var confirmPassword by remember { mutableStateOf("") }
    var passwordVisible by remember { mutableStateOf(false) }
    var error by remember { mutableStateOf<String?>(null) }

    AlertDialog(
        onDismissRequest = onDismiss,
        title = { Text("Passwort ändern") },
        text = {
            Column {
                OutlinedTextField(
                    value = oldPassword,
                    onValueChange = { oldPassword = it; error = null },
                    label = { Text("Aktuelles Passwort") },
                    singleLine = true,
                    visualTransformation = if (passwordVisible) VisualTransformation.None else PasswordVisualTransformation(),
                    trailingIcon = {
                        IconButton(onClick = { passwordVisible = !passwordVisible }) {
                            Icon(if (passwordVisible) Icons.Default.VisibilityOff else Icons.Default.Visibility, contentDescription = null)
                        }
                    },
                    modifier = Modifier.fillMaxWidth(),
                    shape = RoundedCornerShape(12.dp)
                )
                Spacer(modifier = Modifier.height(8.dp))
                OutlinedTextField(
                    value = newPassword,
                    onValueChange = { newPassword = it; error = null },
                    label = { Text("Neues Passwort") },
                    singleLine = true,
                    visualTransformation = if (passwordVisible) VisualTransformation.None else PasswordVisualTransformation(),
                    modifier = Modifier.fillMaxWidth(),
                    shape = RoundedCornerShape(12.dp)
                )
                Spacer(modifier = Modifier.height(8.dp))
                OutlinedTextField(
                    value = confirmPassword,
                    onValueChange = { confirmPassword = it; error = null },
                    label = { Text("Neues Passwort bestätigen") },
                    singleLine = true,
                    visualTransformation = if (passwordVisible) VisualTransformation.None else PasswordVisualTransformation(),
                    modifier = Modifier.fillMaxWidth(),
                    shape = RoundedCornerShape(12.dp)
                )
                if (error != null) {
                    Spacer(modifier = Modifier.height(8.dp))
                    Text(error!!, color = MaterialTheme.colorScheme.error, style = MaterialTheme.typography.bodySmall)
                }
            }
        },
        confirmButton = {
            TextButton(onClick = {
                when {
                    oldPassword.isBlank() -> error = "Aktuelles Passwort eingeben"
                    newPassword.length < 4 -> error = "Mindestens 4 Zeichen"
                    newPassword != confirmPassword -> error = "Passwörter stimmen nicht überein"
                    else -> onConfirm(oldPassword, newPassword)
                }
            }) {
                Text("Ändern")
            }
        },
        dismissButton = {
            TextButton(onClick = onDismiss) {
                Text("Abbrechen")
            }
        }
    )
}
